name: deploy_http_func

on: 
  push: 
    branches:
      - master
    paths:
      - http-func/**.go

  # workflow_dispatch:
  #   inputs:
  #     name: 
  #       description: 'deploy target'
  #       required: true
  #       default: 'dev'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    # https://github.com/google-github-actions/setup-gcloud
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: http-func deploy 
      working-directory: ./http-func
      run: | 
        gcloud functions deploy MyFunctionTutorial --trigger-http --runtime go113